### ISSUE TITLE
[Feature request] search for a word instead of only highlighting

### ISSUE THREAD

**Issue by jlemonde** [farshed/duofolio#1]
Hi! I've just tried out your new app! Congrats for your work!!

I figured out that the only way to look for a definition was to find a word in the text and highlight it. However some words are conjugated or inflected so the trick isn't as straightforward. For those cases I would fancy a feature that allows the user to search specifically for the definition of a word that they would type in themself. Is this easily feasible?

**Comment by farshed** [comment]
Yes, its a good idea and it'll be available in the coming release.

**Comment by farshed** [comment]
Hey, I just released an update. It now supports what you asked. Feel free to reopen this if you don't find the solution sufficient.
