### ISSUE TITLE
Speaking source / target language

### ISSUE THREAD

**Issue by threenplusone** [farshed/duofolio#15]
When I click the "speak" button for the either the source or target language, it announces the way that written word would be pronounced in English.

I can see from [here](https://github.com/farshed/duofolio/blob/master/src/components/DictionaryModal.js#L31) that is it picking the source language, so it is likely that I am doing something wrong in the app. But I cannot work out what that is.

Source language - Danish
Target language - English
Example word - "og" (should be a silent 'g')

**Comment by farshed** [comment]
Interesting. Just tested it out on my device with source language set to English and target as Danish. All the words are pronounced correctly.
(tested by comparing the pronunciation with google translate)

**Comment by farshed** [comment]
Could be an edge-case of some sort. Have you tried with other languages? Also make sure you have the TTS Danish language pack installed in your phone (It's usually taken care of automatically but could be the cause of issue)
Would love to look into it if you can provide some additional information like Android OS version, Google TTS Engine version?

**Comment by threenplusone** [comment]
Thank you so much Faisal!

The preferred engine on my phone was set to "Samsung text-to-speech engine", which does not download the voices automatically.

Changing it to "Google Text-to-speech Engine" works perfectly.
All voices are working without issue now.

Amazing app!
