### ISSUE TITLE
I would like to help you to add support for italian.

### ISSUE THREAD

**Issue by gerzin** [farshed/duofolio#2]
How do I do it? Can't find files to translate.

**Comment by failin3** [comment]
You'll need to find an Italian dictionary ["in a digital, computer-readable format"](https://www.reddit.com/r/languagelearning/comments/inlfnq/just_released_an_app_that_helps_you_read_books_in/g4878f4/), like csv, json, xml, etc. 

Currently the interface only works in English and big changes need to made to make other languages available.

**Comment by farshed** [comment]
Hey @gerzin and @failin3. No need to look for dictionaries as Duofolio is moving away from this approach. I'm working on making it dependant on Google Translate instead so it can support all the major languages.
