### ISSUE TITLE
[Suggestion] Use epubjs-rn instead of epubjs

### ISSUE THREAD

**Issue by rafaelsaback** [farshed/duofolio#8]
I saw that you did some work to integrate epubjs to the RN environment. Have you considered using their [epubjs-rn](https://github.com/futurepress/epubjs-rn) package instead? I think it could help removing a lot of boilerplate code.

If you've tried it and faced some issues, could you let me know what has happened?

**Comment by farshed** [comment]
Hey Rafael, I haven't tried epubjs-rn. It seems unmaintained and there are a lot of open issues about it not being compatible with RN 0.60+.

**Comment by rafaelsaback** [comment]
Got it, just wanted to know. Now that you've mentioned, I've noticed the many open issues they have and that the last commit was done December last year...
